Gdk::Window: get_frame_extents(): Avoid infinite recursion.
Found by this warning from clang++:
window.cc:598:1: error: all paths through this function will call itself [-Werror,-Winfinite-recursion]

This was caused by ths commit:
https://git.gnome.org/browse/gtkmm/commit/gdk/src/window.hg?id=da86805ec88ce5277255606c0d0ebac6486b96cb