gtk-demo/demowindow—Don't use C++14 auto deduction
I broke this in 152fe12c6fe2960c98665c488d6d48a1d9e11f8b back in 2017 :O
It seems it only got noticed now I set warnings as errors & `make check`

>>>
/home/daniel/jhbuild/checkout/gnome/gtkmm-3/demos/gtk-demo/demowindow.cc:54:1:
error: ‘demo_columns’ function uses ‘auto’ type specifier without trailing return type
   54 | const auto& demo_columns()
      | ^~~~~
/home/daniel/jhbuild/checkout/gnome/gtkmm-3/demos/gtk-demo/demowindow.cc:54:1:
note: deduced return type only available with ‘-std=c++14’ or ‘-std=gnu++14’
>>>