recentinfo.hg: Fix Visual Studio build (error C2375)
Nowadays, gtk has its visibility macros generated and make use of
__declspec(dllimport) in addition to __declspec(dllexport), so we must decorate
the `void gtk_recent_info_unref(GtkRecentInfo* info);` prototype with
`GDK_AVAILABLE_IN_ALL`, so that we don't end up with warnings and errors when
we include the GDK headers when building this code.

So, just include gtk/gtk.h and drop the extern "C" portion here, since
it is covered by including gtk/gtk.h.